import { createFileRoute } from "@tanstack/react-router";
import { ArrowUpRight, Check, CircleDollarSign, Clock3, Grid2X2, List, Package, Plus, ShieldCheck, Sparkles, X } from "lucide-react";
import { useState } from "react";
import { AddProductDialog } from "@/components/renthub/AddProductDialog";
import { AppHeader } from "@/components/renthub/AppHeader";
import { TrustScoreDialog } from "@/components/renthub/TrustScoreDialog";
import { Button } from "@/components/ui/button";
import { listings } from "@/lib/renthub-data";

export const Route = createFileRoute("/dashboard")({
  head: () => ({ meta: [
    { title: "Owner dashboard — RentHub" },
    { name: "description", content: "Manage your RentHub listings, rental requests, earnings and trust score." },
    { property: "og:title", content: "RentHub owner dashboard" },
    { property: "og:description", content: "Your rental business and reputation in one place." },
    { property: "og:type", content: "website" },
    { name: "twitter:card", content: "summary_large_image" },
  ]}),
  component: DashboardPage,
});

function DashboardPage() {
  const [view, setView] = useState<"grid" | "table">("grid");
  const [requests, setRequests] = useState(["request-1", "request-2"]);
  return <div className="min-h-screen bg-background"><AppHeader /><main className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8">
    <div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] font-bold uppercase text-primary">Owner workspace</p><h1 className="mt-2 text-3xl font-extrabold sm:text-4xl">Good evening, Arunav.</h1><p className="mt-2 text-sm text-muted-foreground">Here’s what’s happening with your rentals.</p></div><AddProductDialog trigger={<Button size="lg"><Sparkles /> Add product with AI</Button>} /></div>
    <section className="mt-8 grid gap-4 lg:grid-cols-12">
      <div className="relative overflow-hidden rounded-3xl border border-primary/20 bg-card p-6 lg:col-span-7"><div className="absolute right-0 top-0 h-40 w-40 rounded-full bg-primary/10 blur-3xl" /><div className="relative grid gap-6 sm:grid-cols-[auto_1fr]"><div className="relative grid size-32 place-items-center rounded-full bg-[conic-gradient(var(--color-primary)_92%,var(--color-muted)_0)]"><div className="grid size-25 place-items-center rounded-full bg-card"><span className="text-4xl font-extrabold">92</span></div></div><div><div className="flex items-center gap-2"><ShieldCheck className="text-trust" /><span className="rounded-full bg-trust-soft px-3 py-1 text-xs font-bold text-trust">Excellent</span></div><h2 className="mt-3 text-2xl font-extrabold">Your reputation stands out.</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">You’re in the top 8% of owners. Keep up your perfect fulfillment record.</p><TrustScoreDialog trigger={<Button variant="link" className="mt-3 h-auto p-0">View full breakdown <ArrowUpRight /></Button>} /></div></div><div className="relative mt-7 grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Profile","20/20"],["Listings","22/25"],["Fulfillment","32/35"],["Reliability","18/20"]].map(([label,value]) => <div key={label} className="rounded-xl bg-secondary p-3"><span className="text-xs text-muted-foreground">{label}</span><strong className="mt-1 block">{value}</strong></div>)}</div></div>
      <div className="grid grid-cols-2 gap-4 lg:col-span-5"><Metric icon={<Package />} label="Listed products" value="12" delta="+2 this month" /><Metric icon={<Clock3 />} label="Active rentals" value="4" delta="3 due this week" /><Metric icon={<CircleDollarSign />} label="Total earnings" value="$3,840" delta="+18% this month" /><AddProductDialog trigger={<Button variant="outline" className="h-full min-h-32 flex-col rounded-2xl border-dashed border-primary/40 bg-accent/30"><Plus className="size-6" /><span>Add a product</span></Button>} /></div>
    </section>
    <section className="mt-12"><div className="flex items-center justify-between"><div><p className="text-[11px] font-bold uppercase text-primary">Inventory</p><h2 className="mt-1 text-2xl font-extrabold">My products</h2></div><div className="flex rounded-xl border border-border bg-secondary p-1"><Button variant={view === "grid" ? "default" : "ghost"} size="icon" aria-label="Grid view" onClick={() => setView("grid")}><Grid2X2 /></Button><Button variant={view === "table" ? "default" : "ghost"} size="icon" aria-label="Table view" onClick={() => setView("table")}><List /></Button></div></div>
      {view === "grid" ? <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{listings.map((item, index) => <div key={item.id} className="overflow-hidden rounded-2xl border border-border bg-card"><div className="relative aspect-[4/3]"><img src={item.image} alt={item.title} loading="lazy" width={1200} height={900} className="h-full w-full object-cover" /><span className={`absolute left-3 top-3 rounded-full px-2.5 py-1 text-[10px] font-bold uppercase ${index === 1 ? "bg-accent text-accent-foreground" : "bg-trust-soft text-trust"}`}>{index === 1 ? "Rented out" : "Available"}</span></div><div className="p-4"><p className="font-bold">{item.title}</p><p className="mt-1 text-sm text-muted-foreground">${item.price}/day</p></div></div>)}</div> : <div className="mt-6 overflow-x-auto rounded-2xl border border-border"><table className="w-full min-w-150 text-left text-sm"><thead className="bg-secondary text-xs uppercase text-muted-foreground"><tr><th className="p-4">Product</th><th className="p-4">Status</th><th className="p-4">Rate</th><th className="p-4">Rentals</th></tr></thead><tbody>{listings.map((item,index) => <tr key={item.id} className="border-t border-border"><td className="p-4 font-semibold">{item.title}</td><td className="p-4 text-trust">{index === 1 ? "Rented out" : "Available"}</td><td className="p-4">${item.price}/day</td><td className="p-4">{item.reviews}</td></tr>)}</tbody></table></div>}
    </section>
    <section className="mt-12"><p className="text-[11px] font-bold uppercase text-primary">Needs your attention</p><h2 className="mt-1 text-2xl font-extrabold">Rental requests</h2><div className="mt-6 grid gap-4 lg:grid-cols-2">{requests.length ? requests.map((id,index) => <RequestTicket key={id} index={index} onRemove={() => setRequests((items) => items.filter((item) => item !== id))} />) : <div className="col-span-full rounded-2xl border border-dashed border-border p-12 text-center text-sm text-muted-foreground">You’re all caught up.</div>}</div></section>
  </main></div>;
}

function Metric({ icon, label, value, delta }: { icon: React.ReactNode; label: string; value: string; delta: string }) { return <div className="rounded-2xl border border-border bg-card p-5"><span className="text-primary [&_svg]:size-5">{icon}</span><p className="mt-5 text-2xl font-extrabold">{value}</p><p className="mt-1 text-xs font-semibold">{label}</p><p className="mt-2 text-[10px] text-muted-foreground">{delta}</p></div>; }
function RequestTicket({ index, onRemove }: { index: number; onRemove: () => void }) { const item = listings[index]; if (!item) return null; return <article className="rounded-2xl border border-border bg-card p-4"><div className="grid grid-cols-[72px_1fr_auto] gap-4"><img src={item.image} alt="" className="size-18 rounded-xl object-cover" /><div className="min-w-0"><p className="truncate font-bold">{item.title}</p><p className="mt-1 text-xs text-muted-foreground">Requested by {index ? "Leena S." : "Rohan K."}</p><span className="mt-2 inline-flex items-center gap-1 text-xs font-bold text-trust"><ShieldCheck className="size-3.5" /> Trust {index ? 94 : 97}</span></div><strong className="text-sm">${item.price * 3}</strong></div><div className="mt-4 flex items-center justify-between border-t border-border pt-4"><span className="text-xs text-muted-foreground">Sep {18 + index} – {21 + index} · 3 days</span><div className="flex gap-2"><Button variant="outline" size="sm" className="text-destructive" onClick={onRemove}><X /> Reject</Button><Button variant="trust" size="sm" onClick={onRemove}><Check /> Approve</Button></div></div></article>; }